jobs:
- template: template.yml
  parameters:
    name: Ubuntu_20_04_python37
    vmImage: 'ubuntu-20.04'
    py_maj: 3
    py_min: 7

- template: template.yml
  parameters:
    name: macOS_10_15_python37
    vmImage: 'macOS-10.15'
    py_maj: 3
    py_min: 7

- template: template.yml
  parameters:
    name: Windows_VS2019_python37
    vmImage: 'windows-2019'
    py_maj: 3
    py_min: 7

- template: template.yml
  parameters:
    name: Ubuntu_20_04_python38
    vmImage: 'ubuntu-20.04'
    py_maj: 3
    py_min: 8

- template: template.yml
  parameters:
    name: macOS_10_15_python38
    vmImage: 'macOS-10.15'
    py_maj: 3
    py_min: 8

- template: template.yml
  parameters:
    name: Windows_VS2019_python38
    vmImage: 'windows-2019'
    py_maj: 3
    py_min: 8

- template: template.yml
  parameters:
    name: Ubuntu_20_04_python39
    vmImage: 'ubuntu-20.04'
    py_maj: 3
    py_min: 9

- template: template.yml
  parameters:
    name: macOS_10_15_python39
    vmImage: 'macOS-10.15'
    py_maj: 3
    py_min: 9

- template: template.yml
  parameters:
    name: Windows_VS2019_python39
    vmImage: 'windows-2019'
    py_maj: 3
    py_min: 9

