jobs:
- template: template.yml
  parameters:
    name: Ubuntu_22_04_python310
    vmImage: 'ubuntu-22.04'

- template: template.yml
  parameters:
    name: macOS_11_python310
    vmImage: 'macOS-11'

- template: template.yml
  parameters:
    name: Windows_VS2022_python310
    vmImage: 'windows-2022'
