channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - pip:
    - z3-solver==4.13.3.0
    - matplotlib
    - plotly
    - kaleido
    - ipywidgets
    - isodate
    - ipympl
    - psutil
    - XlsxWriter
    - coverage
    - pydantic
    - rich
    - pandas
    - pyarrow
    - pytest
    - -e .
