channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - matplotlib=3.3.3
  - plotly=4.13.0
  - pandas=1.1.4
  - xlrd=1.2.0
  - xlsxwriter=1.3.7
  - pip:
    - z3-solver==4.8.9.0
