channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - pip:
    - z3-solver==4.11.2
    - matplotlib==3.4.1
    - plotly== 4.14.3
    - kaleido== 0.2.1
    - ipywidgets== 7.6.3
    - isodate==0.6.0
    - ipympl==0.7.0
    - psutil==5.8.0
    - -e .
